### ISSUE TITLE
 object 'collect_log' not found  

### ISSUE THREAD

**Issue by Royzhang14444** [vosonlab/vosonSML#57] opened 2024-05-24 07:00 UTC
Hello, I tried to run the example in the 'README', and got the error says    object 'collect_log' not found

 ># collect a listing of the 25 top threads by upvote of all time
> collect_rd_listing <- Authenticate("reddit") |>
+     Collect(endpoint = "listing", subreddits = subreddits,
+             sort = "top", period = "all", max = 25,
+             writeToFile = TRUE, verbose = TRUE)

The following is the error message:
No listings were collected.
Error in Collect.listing.reddit(Authenticate("reddit"), endpoint = "listing",  : 
  object 'collect_log' not found

**Comment by bryn-g** [comment] 2024-05-25 06:32
Thanks very much for the issue report @Royzhang14444, this is a duplicate of #56.

**Comment by bryn-g** [comment] 2024-07-21 08:50
Error is fixed in 5fa70dc.

**Closed by bryn-g** 2024-07-21 08:50 UTC
Labels: bug, duplicate
